// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqoiMV_yQblMJ67zArAzwUOjqiuj1TJEE',
    appId: '1:98918841286:android:bbcaabcb0bb50b2ae450c7',
    messagingSenderId: '98918841286',
    projectId: 'chatapp-92fa0',
    storageBucket: 'chatapp-92fa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUgG7mmt1vU_aUFnYDb8avXLZcKn9LoLk',
    appId: '1:98918841286:ios:1182c8fc8161f924e450c7',
    messagingSenderId: '98918841286',
    projectId: 'chatapp-92fa0',
    storageBucket: 'chatapp-92fa0.appspot.com',
    androidClientId: '98918841286-feen1u12gdvike242o1rmltoad4uiq2m.apps.googleusercontent.com',
    iosClientId: '98918841286-2f5sbeamp23eiblrf0khb0s58q37h675.apps.googleusercontent.com',
    iosBundleId: 'com.io.kodionProjects',
  );
}
